export const projectdata=[
    {
       url:"https://oktayshakirov.com/assets/images/projects/clonings.png",
       name:"Clonings AI",
       title:"Frontend",
       subtitle:"React.js | Chakra UI",
       suburlp:"https://clonings.ai/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/cortextual.png",
       name:"Cortextual AI Website",
       title:"Frontend",
       subtitle:"Wordpress",
       suburlp:"https://cortextual.ai/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/FashioSwap.png",
       name:"FashionSwap App",
       title:"Design + Frontend",
       subtitle:"Figma | React.js | Chakra UI",
       suburlp:"https://www.fashionswap.ai/",
    },
   
    {
       url:"https://oktayshakirov.com/assets/images/projects/contour.png",
       name:"Inventory Management App",
       title:"Design + Frontend",
       subtitle:"Figma | React.js | Chakra UI",
       suburlp:"https://www.contour.bg/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/mybestwishes.png",
       name:"MyBestWishes AI Generator",
       title:"Design + Frontend",
       subtitle:"Figma | React.js | Chakra UI",
       suburlp:"https://mybestwishes.ai/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/myworkphoto.png",
       name:"MyWorkPhoto AI Generator",
       title:"Design + Frontend",
       subtitle:"Figma | React.js | Chakra UI",
       suburlp:"https://myworkphoto.com/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/undressninja.png",
       name:"Undress Ninja App (NSFW)",
       title:"Frontend",
       subtitle:"React.js | Chakra UI",
       suburlp:"https://undressninja.com/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/ogno-dashboard.png",
       name:"Ogno Marketing Dashboard",
       title:"Frontend + Backend",
       subtitle:"React.js | Strapi.js | MySQL",
       suburlp:"https://ogno.netlify.app/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/bayer-askmed.png",
       name:"AskMed By Bayer",
       title:"Frontend",
       subtitle:"Drupal | PHP | CSS",
       suburlp:"https://www.medicalinformation.bayer.com/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/enemzet.png",
       name:"EnEmZet Online Store",
       title:"Frontend + Backend",
       subtitle:"Next.js | TypeScript | MySQL",
       suburlp:"https://enemzet.store/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/tinnitus-blog.png",
       name:"Beyond Tinnitus Blog",
       title:"Frontend",
       subtitle:"Next.js | TypeScript | Material-UI",
       suburlp:"https://www.beyondtinnitus.online/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/watch_store.png",
       name:"Timeazon Online Store",
       title:"Frontend + Backend",
       subtitle:"React.js | Node.js | MySQL | Sass",
       suburlp:"https://timeazon.netlify.app/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/weather-app.png",
       name:"Weather App",
       title:"Frontend",
       subtitle:"JavaScript | API's | CSS",
       suburlp:"https://oktayshakirov.github.io/weather-app/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/pigletz-matching.png",
       name:"Pigletz Memory Game",
       title:"Frontend",
       subtitle:"JavaScript | CSS",
       suburlp:"https://oktayshakirov.github.io/pigletz-matching/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/team-manager.png",
       name:"Team Management Tool",
       title:"Frontend + Backend",
       subtitle:"PHP | CSV Data | CSS",
       suburlp:"https://oktayshakirov.000webhostapp.com/team-manager/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/portfolio.png",
       name:"Personal Portfolio",
       title:"Frontend",
       subtitle:"JavaScript | CSS | HTML",
       suburlp:"https://oktayshakirov.com/",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/quiz.png",
       name:"Quiz Time",
       title:"Frontend",
       subtitle:"PHP | CSS | HTML",
       suburlp:"https://oktayshakirov.000webhostapp.com/quiz",
    },
    {
       url:"https://oktayshakirov.com/assets/images/projects/berlinew.jpg",
       name:"BerliNEW Android App",
       title:"Frontend",
       subtitle:"Wordpress | Android SDK",
       suburlp:"https://berlinew.wordpress.com/",
    },
    
]